# Based on these instructions:
# https://jekyllrb.com/docs/continuous-integration/travis-ci/

language: ruby

rvm:
- 2.4.4

install: bundle install

script:
  - set -e
  - echo 'Running "jekyll build"...' && echo -en 'travis_fold:start:build\\r'
  - bundle exec jekyll build
  - echo -en 'travis_fold:end:build\\r'

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
