#
# This file contains configuration flags to customize your site
#

# theme: jekyll-theme-minimal


# ---------------------------------------------------------------------------
# Theme variables for jekyll-theme-minimal
# https://github.com/pages-themes/minimal


# Name of your site (displayed in the header)
title: Rush

# Short bio or description (displayed in the header)
description: none

# Location of the logo
logo:

# "true" or "false" to indicate whether to provide a download URL
show_downloads: false

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:
# ---------------------------------------------------------------------------


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Microsoft/web-build-tools
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.rushjs.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:categories/:year/:title

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Settings for https://github.com/algolia/jekyll-algolia
# Our login account is: @rushbot (GitHub alias)
algolia:
  application_id: 'MMJOXTLRT5'
  index_name: 'rushjs.io'
  search_only_api_key: '01b32d3d6bf177d93c0bac0fd71ae7ba'

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-algolia # Create search index for Algolia
#  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
